---
apiVersion: v1
kind: Namespace
metadata:
  name: invalid-this-is-a-kustomize-error
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flux-admin
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flux-admin
subjects:
- kind: ServiceAccount
  name: flux-admin