apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: velero-clusterrole
rules:
  - apiGroups: [""]
    resources:
      - persistentvolumes
      - namespaces
    verbs: ["get", "list", "watch"]
  - apiGroups: ["velero.io"]
    resources: ["backups", "restores", "deletebackuprequests", "downloadrequests", "uploadrequests"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get"]
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: velero-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: velero-clusterrole
subjects:
  - kind: ServiceAccount
    name: velero
    namespace: velero